const GET_LOCATION_DATA = 'GET_LOCATION_DATA';
const FILTER_BY_TITLE = 'FILTER_BY_TITLE';
const FILTER_BY_YEAR = 'FILTER_BY_YEAR';
const RESET_DATA = 'RESET_DATA';


export { GET_LOCATION_DATA, FILTER_BY_TITLE, FILTER_BY_YEAR, RESET_DATA };
